### ISSUE TITLE
Finding the culprit of the -infinity health bug. Give me your logs!

### ISSUE THREAD

**Issue by RicoValdezio** [RicoValdezio/RoR2-GeneticsArtifact#2]
This thread will remain open until the health bug is found and resolved. Until then, feel free to drop your logs here if you run into the bug, as every example helps for narrowing down the suspects.

**Comment by RicoValdezio** [comment]
This log doesn't actually have the bug in it, its just a test.
[LogOutput.log](https://github.com/RicoValdezio/RoR2-GeneticsArtifact/files/5372551/LogOutput.log)

**Comment by SorcererPonse** [comment]
Had encountered the bug early on previously, but this time it was very late in, at about 197:28 on stage 20(I think) on Monsoon, NaNs start appearing in the tracked genetics but no accidental deaths are tracked. That, or the constant spam of:

`[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area`

blocked them out before I could catch it. Due to this, the LogOutput.log file is massive, but I have a link to it [here](https://cdn.discordapp.com/attachments/562711077453037589/765883047060176906/LogOutput.log).

**Comment by SorcererPonse** [comment]
Another run where the bug was encountered, once again after a very long time in-game. Despite building tons of glasses and other damage items it managed to remain stable, but something happened 178 minutes in on stage 14 on Monsoon that made everything go out of whack. I'll link the LogOutput.log file [here](https://cdn.discordapp.com/attachments/562711077453037589/766282494785093642/LogOutput.log) as, once again, the file is too big to upload here. I'll also link a screenshot of my endgame stats [here](https://cdn.discordapp.com/attachments/392141934581514247/766283065508888656/20201015075134_1.jpg) just in case you need it. I'll also try getting this with a normal character next time, I had luck with Rex last time but I want to see if it'll happen on Commando.

**Comment by RicoValdezio** [comment]
Going to mark this as closed until further notice. Haven't had any reports since 1.4.4 dropped, but this can be reopened if need be.
