### ISSUE TITLE
Readd the Gene-Specific Configuration that was removed with v4

### ISSUE THREAD

**Issue by zCap80** [RicoValdezio/RoR2-GeneticsArtifact#38]
Would it be possible to adjust the speed stat that an enemy can inherit so scaling can be boosted without feeling like you need movement items to survive?

**Comment by RicoValdezio** [comment]
This gene-specific limits/scaling was - at one point - included in the config as something users could tweak to their liking. I think it was originally cut due to the amount of "bloat" these options introduced, and I never thought to re-add it as part of the newest rewrite. I'll spin up a branch over the weekend and see if I can't find a way to bring it back.

**Comment by RicoValdezio** [comment]
Just release 4.5.0 to get this back in. Hopefully the little bit of documentation in the config explains it well enough, but if not feel free to ask here. Going to close the issue, but you should still be able to comment.
